# Generated by Django 3.1 on 2022-08-30 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('birth', models.DateField()),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
